[package]
name = "cmb"
version = "0.1.0"
authors = ["kento tajiri <k.denjiry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "3.5.0"
